### ISSUE TITLE
relocate "posts" to create a different URL

### ISSUE THREAD

**Issue by igalic** [Dalgona/Serum#136]
I want to look and sound smart when writing blog posts, and for that i would like my "posts" to show up under the URI `/thoughts/`

This could be done with a configuration option in `serum.exs` which would assign "posts" a different name.

(Whether the directory on disk needs to change for this or not, I'm not sure. It might makes things easier because more consistent 🤷‍♀️️)

**Comment by Dalgona** [comment]
You're right. We could let users have more fine-grained control over file paths for a blog, by adding some configuration items to `serum.exs`. And considering your last words, I could come up with an idea which looks like:

```elixir
%{
  # Path to a directory which holds source files for your blog posts.
  # Defaults to `"posts"`.
  posts_path: "thoughts",

  # Path in an output directory which your rendered blog posts will be written to.
  # Defaults to the value of `:posts_path`.
  # (Obviously, the default value will be `"posts"`
  # if `:posts_path` is not explicitly given.)
  posts_url: "thoughts"
  # Yes, the above line can be omitted in your case.

  # Path in an output directory which the tag pages will be written to.
  # Defaults to `"tags"`.
  tags_url: "thoughts/tags"
}
```

**Comment by igalic** [comment]
i didn't even think of tags! but, of course they have to be relocated, too.

**Comment by igalic** [comment]
i started looking into contributing this patch myself, and, it's been too long since i looked at the code 🙇‍♀️️ i have no idea where to start 😵️

**Comment by Dalgona** [comment]
I should apologize for _still_ not having a contribution guides. 😅💦 If you don't mind, please let me implement this feature.

Roughly, I would...
- [ ] Add the new keys to `Serum.Project` struct,
  (`lib/serum/project.ex`)
- [ ] Make Serum recognize and validate those keys,
  (`lib/serum/project/elixir_validator.ex`)
- [ ] Enable `Serum.Build.FileLoader.Posts` to load blog post files from another directory,
  (`lib/serum/build.ex`
  &rarr; `lib/serum/build/file_loader.ex`
  &rarr; `lib/serum/build/file_loader/posts.ex`)
- [ ] Make it possible to write rendered blog posts in another directory,
  (`lib/serum/build/file_processor/post.ex`, `lib/serum/post.ex`)
- [ ] Same thing for post lists (tag pages),
  (`lib/serum/build/file_processor/post_list.ex`, `lib/serum/post_list.ex`)
- [ ] And finally, update affected tests to make sure nothing is broken and the new feature works well.
