### ISSUE TITLE
" serum build" encounter error.how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [Dalgona/Serum#14]
hi.

root@localhost:/usr/local/serum-site/serum-blog# ls
assets  media  pages  posts  serum.json  site  templates
root@localhost:/usr/local/serum-site/serum-blog# serum build
Serum -- Yet another simple static website generator
Version 0.9.0+201702021514. Copyright (C) 2016 Dalgona. <dalgona@hontou.moe>

Reading project metadata `./serum.json'...
Rebuilding Website...
Created directory `./site/`.
Loading templates...
Scanning `./pages/` directory...
Compiling main navigation HTML stub...
⌛  Starting sequential build...
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (CompileError) nofile:5: undefined function site_name/0
        (elixir) src/elixir_expand.erl:544: :elixir_expand.expand_args/2
        (elixir) src/elixir_expand.erl:630: :elixir_expand.expand_remote/7
        (elixir) src/elixir_expand.erl:540: :elixir_expand.expand_arg/2
        (elixir) src/elixir_bitstring.erl:65: :elixir_bitstring.expand_expr/4
        (elixir) src/elixir_bitstring.erl:19: :elixir_bitstring.expand/6
        (elixir) src/elixir_bitstring.erl:12: :elixir_bitstring.expand/4
        (elixir) expanding macro: Kernel.<>/2
        nofile:1: (file)

07:40:03.574 [error] GenServer #PID<0.92.0> terminating
** (CompileError) nofile:5: undefined function site_name/0
    (elixir) src/elixir_expand.erl:544: :elixir_expand.expand_args/2
    (elixir) src/elixir_expand.erl:630: :elixir_expand.expand_remote/7
    (elixir) src/elixir_expand.erl:540: :elixir_expand.expand_arg/2
    (elixir) src/elixir_bitstring.erl:65: :elixir_bitstring.expand_expr/4
    (elixir) src/elixir_bitstring.erl:19: :elixir_bitstring.expand/6
    (elixir) src/elixir_bitstring.erl:12: :elixir_bitstring.expand/4
    (elixir) expanding macro: Kernel.<>/2
    nofile:1: (file)
Last message: {:build, :sequential}
State: {"./", "./site/", %Serum.ProjectInfo{author: "Somebody", author_email: "somebody@example.com", base_url: "/", date_format: "{WDfull}, {D} {Mshort} {YYYY}", list_title_all: "All Posts", list_title_tag: "Posts Tagged ~s", preview_length: 200, site_description: "Welcome to my website!", site_name: "New Website"}}
root@localhost:/usr/local/serum-site/serum-blog#

**Comment by Dalgona** [comment]
The latest snapshot may be broken. Did you run `serum build` on a new project generated with `serum init` command?

**Comment by luckypoem** [comment]
yes,i just did that.so how to fix it?

**Comment by luckypoem** [comment]
still not ok.

root@localhost:/usr/local/serum-site/serum-blog# serum build
Serum -- Yet another simple static website generator
Version 0.9.0+201702021514. Copyright (C) 2016 Dalgona. <dalgona@hontou.moe>

Reading project metadata `./serum.json'...
Rebuilding Website...
Created directory `./site/`.
Loading templates...
Scanning `./pages/` directory...
Compiling main navigation HTML stub...
⌛  Starting sequential build...
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (CompileError) nofile:9: undefined function site_description/0
        (elixir) src/elixir_expand.erl:544: :elixir_expand.expand_args/2
        (elixir) src/elixir_expand.erl:630: :elixir_expand.expand_remote/7
        (elixir) src/elixir_expand.erl:540: :elixir_expand.expand_arg/2
        (elixir) src/elixir_bitstring.erl:65: :elixir_bitstring.expand_expr/4
        (elixir) src/elixir_bitstring.erl:19: :elixir_bitstring.expand/6
        (elixir) src/elixir_bitstring.erl:12: :elixir_bitstring.expand/4
        (elixir) expanding macro: Kernel.<>/2
        nofile:1: (file)

03:49:27.927 [error] GenServer #PID<0.92.0> terminating
** (CompileError) nofile:9: undefined function site_description/0
    (elixir) src/elixir_expand.erl:544: :elixir_expand.expand_args/2
    (elixir) src/elixir_expand.erl:630: :elixir_expand.expand_remote/7
    (elixir) src/elixir_expand.erl:540: :elixir_expand.expand_arg/2
    (elixir) src/elixir_bitstring.erl:65: :elixir_bitstring.expand_expr/4
    (elixir) src/elixir_bitstring.erl:19: :elixir_bitstring.expand/6
    (elixir) src/elixir_bitstring.erl:12: :elixir_bitstring.expand/4
    (elixir) expanding macro: Kernel.<>/2
    nofile:1: (file)
Last message: {:build, :sequential}
State: {"./", "./site/", %Serum.ProjectInfo{author: "Somebody", author_email: "s                                                                                                 omebody@example.com", base_url: "/", date_format: "{WDfull}, {D} {Mshort} {YYYY}                                                                                                 ", list_title_all: "All Posts", list_title_tag: "Posts Tagged ~s", preview_lengt                                                                                                 h: 200, site_description: "Welcome to my website!", site_name: "New Website"}}
root@localhost:/usr/local/serum-site/serum-blog#

**Comment by luckypoem** [comment]
expecting the patches

**Comment by Dalgona** [comment]
Oh I think I missed one thing... You also need to remove empty parentheses at the end of `site_description()` in `base.html.eex`. Sorry!

**Comment by luckypoem** [comment]
now it's ok

**Comment by luckypoem** [comment]
but i cloned https://github.com/Dalgona/serum-site:
root@localhost:/usr/local/serum-site# git clone https://github.com/Dalgona/serum-site serum-sample-site
root@localhost:/usr/local/serum-site# cd serum-sample-site
root@localhost:/usr/local/serum-site/serum-sample-site# ls
assets  media  pages  posts  serum.json  site  templates
root@localhost:/usr/local/serum-site/serum-sample-site# serum build
Serum -- Yet another simple static website generator
Version 0.9.0+201702021514. Copyright (C) 2016 Dalgona. <dalgona@hontou.moe>

Reading project metadata `./serum.json'...
Rebuilding Website...
Created directory `./site/`.
Loading templates...
Scanning `./pages/` directory...
Compiling main navigation HTML stub...
** (EXIT from #PID<0.91.0>) an exception was raised:
    ** (CompileError) nofile:2: expected variable "assigns" to expand to an existing variable or be part of a match
        (elixir) expanding macro: Kernel.var!/1
        nofile:2: (file)
        (elixir) expanding macro: Kernel.<>/2
        nofile:1: (file)
        (elixir) expanding macro: Kernel.<>/2
        nofile:1: (file)
        (elixir) expanding macro: Kernel.<>/2
        nofile:1: (file)

04:14:45.878 [error] GenServer #PID<0.92.0> terminating
** (CompileError) nofile:2: expected variable "assigns" to expand to an existing variable or be part of a match
    (elixir) expanding macro: Kernel.var!/1
    nofile:2: (file)
    (elixir) expanding macro: Kernel.<>/2
    nofile:1: (file)
    (elixir) expanding macro: Kernel.<>/2
    nofile:1: (file)
    (elixir) expanding macro: Kernel.<>/2
    nofile:1: (file)
Last message: {:build, :sequential}
State: {"./", "./site/", %Serum.ProjectInfo{author: "Dalgona.", author_email: "dalgona@hontou.moe", base_url: "/serum-s                                                          ample/", date_format: "{YYYY}-{0M}-{0D}", list_title_all: "All Posts", list_title_tag: "Posts Tagged ~s", preview_lengt                                                          h: 200, site_description: "This website shows what Serum can do.", site_name: "Sample Website"}}
root@localhost:/usr/local/serum-site/serum-sample-site#

how to fix it?

**Comment by Dalgona** [comment]
Yeah, the same reason. Source code for the sample website has not yet been migrated. I'll get everything fixed by today... I apologize for your inconvenience! :joy:

**Comment by Dalgona** [comment]
I apologize for late reply. Patches were pushed to this repository and `serum-site`. Please pull the latest commits and try building the site again.

**Comment by luckypoem** [comment]
tks.
pagination can be implemented?

**Comment by Dalgona** [comment]
Yes, I'm planning to add a lot of new features. But I'm not sure when those features become available to public, because I'm currently busy due to campus schedules. 😢

I'm closing this issue because your main problem seems to be resolved now. You can open a new issue regarding to a new pagination features, if you want.
