### ISSUE TITLE
code snippet not detected

### ISSUE THREAD

**Issue by sensiblearts** [Dalgona/Serum#150]
This does not render as code:
<pre>
```
def dsomething() do
    junk()
end
```
</pre>

whereas, Earmark does.

**Comment by Dalgona** [comment]
Serum uses Earmark to process markdown pages, so it should properly recognize code blocks too if Earmark does. But Earmark has always been problematic when rendering code blocks, especially when the they are indented (i.e. it's nested inside a list item).

Could you please provide more information about your issue?

- Which version of Serum are you using?
- Please post the part of your page source which caused this issue (of course, with sensitive information redacted).

**Comment by sensiblearts** [comment]
I am terribly sorry -- it works fine.

May I say, I'm impressed with how easy it was to get a blog going.

**Comment by sensiblearts** [comment]
Pardon me: Can you recommend an elixir lib to add syntax highlighting? JS approach is fine, too.

**Comment by sensiblearts** [comment]
@Dalgona Thanks, I figured it out. I downloaded prism.js and Serum detected the added js/css files, and it works like a charm when I do it like this:
<pre>
```language-elixir
def dosomething() do
  test()
end
</pre>

**Comment by Dalgona** [comment]
As far as I know, the only syntax highlighter library available in Hex.pm is "Makeup", which is used by ExDoc. But currently Makeup is only capable of highlighting Elixir codes (with the _additional_ lexer package called `makeup_elixir`).

Thanks to its extensible design, Makeup can support other programming languages by adding lexer packages, but the Elixir lexer (`makeup_elixir`) is the only one available... for now. 😢
