### ISSUE TITLE
View Helpers?

### ISSUE THREAD

**Issue by ecognium** [Dalgona/Serum#165]
First of, I don't know if issues is the right away to ask this question.. apologies if there is a different place for it. 

I am looking to create an `index.html` page that automatically picks up the posts that are marked as 'highlight' and some 'ranking'.  I was going to use `@all_posts` and some some custom logic to figure which subset of posts should be used and possibly tag them whether they should be in the Hero section, etc. It may end up being not so trivial logic.  

Instead of writing all the logic inside the template, I was thinking it will be nice to do them inside a `ViewHelper` module. However, I am not sure if there is a way for users to provide this? If not, any other recommendation on how this can be achieved? 

 Thanks!

**Comment by Dalgona** [comment]
First of all, I apologize for late response. I couldn't pay attention to this project for a quite long time.

Every Serum project is also a Mix project, which means you can define any module inside the `lib` directory. And you can use any functions or macros from any module (i.e. standard Elixir modules, modules from Mix dependencies, and of course, your own modules in the `lib` directory) in your templates.

The `mix serum.new` command does not create the `lib` directory when creating a new Serum project. Simply create one, put your modules inside it, and use them in your templates.
