### ISSUE TITLE
v1: use pretty urls for posts

### ISSUE THREAD

**Issue by dch** [Dalgona/Serum#167]
thanks for serum! Is it possible to have posts generate a pretty url (suffix-free) instead of having `.html` appended?

This works for pages:

```
pages/about
pages/about/index.md
pages/index.md
pages/license
pages/license/index.md
pages/talks
...
```

but not for posts.

I'd like to have

- https://people.freebsd.org/~dch/posts/2021-02-23-sideloading-freebsd

instead of:

- https://people.freebsd.org/~dch/posts/2021-02-23-sideloading-freebsd.html

If you have a suggestion or pointer how to do this, let me know I'll have a crack at it.

**Comment by Dalgona** [comment]
Sorry for a late response, I wasn't able to pay attention to this project for a while.

The feature you're describing could be achieved by having an option in project configuration (`serum.exs`) like this:

```elixir
# In serum.exs:
{
  # Disable (this will be the default value for compatibility.)
  pretty_urls: false,

  # Enable for both pages and posts
  pretty_urls: true,

  # Enable only for pages
  pretty_urls: :pages,

  # Enable only for posts
  pretty_urls: :posts
}
```

However, I think it won't be a trivial job to implement this, since the behavior of template helpers (e.g. `page/1`, `post/1`, etc.) should be different depending on this new option. But yes, this will be shipped in the next release of Serum v1. Thank you for the feature request!

**Comment by Dalgona** [comment]
During the actual implementation of this feature, I have found that pretty URLs for ordinary pages requires complex logic, and I think it would appear quite counterintuitive to users. (And, this is not even what you asked for!)

So pretty page URLs won't make it to the next release. Just pretty blog post URLs. But I'll leave the room for future extensions of this feature though.

```elixir
# In serum.exs:
{
  # Disable (this will be the default value for compatibility.)
  pretty_urls: false,

  # Enable for all kind of pages.
  # At this time, setting it to this value has exactly the same effect as setting it to `:posts`,
  # but its behavior may change in the future and it may break existing links if you already
  # have published your website.
  pretty_urls: true,

  # Enable only for posts
  pretty_urls: :posts
}
```

**Comment by Dalgona** [comment]
This feature has been merged into `v1/master`. I'm not sure when to release a new version, but you can try it now by using the Git version:

```elixir
# In your mix.exs:

defp deps do
  [
    {:serum, github: "Dalgona/Serum", ref: "v1/master"}
  ]
end
```

I'm closing this issue now, but if you encounter any problems regarding pretty URLs, please feel free to reopen it and share your issues.

**Comment by dch** [comment]
awesome - thanks! :heart_eyes_cat:
