### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tmbb** [Dalgona/Serum#17]
I believe this doesn't support windows, right?

**Comment by Dalgona** [comment]
I'm afraid it doesn't, and I'm not sure when I can start working on it. 😢 However, if you're using the latest version of Windows 10, you can try using this within *Windows Subsystem for Linux*. I have tested Serum on WSL platform several times (a long ago though), so it could work quite well...

**Comment by tmbb** [comment]
Ok, don't worry. I'm already writing something custom for my needs. Thanks
