### ISSUE TITLE
Serum command not working in terminal

### ISSUE THREAD

**Issue by djKooks** [Dalgona/Serum#20]
Hello. First, nice to find good elixir project.
I'm following installation http://dalgona.hontou.moe/Serum/getting-started.html, but cannot find command `serum` running after this.

```
$ cd path/to/Serum
$ make
...
Compiling 1 file (.ex)
warning: String.strip/1 is deprecated, use String.trim/1
  lib/mime.ex:30

Generated mime app
==> microscope
Compiling 8 files (.ex)
Generated microscope app
==> serum
Compiling 30 files (.ex)
Generated serum app
Generated escript serum with MIX_ENV=prod
$ serum
-bash: serum: command not found
```

Am I doing something wrong?
Thanks.

**Comment by Dalgona** [comment]
You need to type `./serum` instead of `serum` unless you have copied the program to somewhere else defined in `$PATH`.

**Comment by dragsubil** [comment]
You should run `sudo make install` also if you want to run it directly from your terminal. That will install it in `/usr/local/bin` and you'll be able to run it globally.

**Comment by djKooks** [comment]
@Dalgona @dragsubil Thanks for quick reply! Now it works, so I'll close this one.
