### ISSUE TITLE
Add support for Canonical link element

### ISSUE THREAD

**Issue by wevtimoteo** [Dalgona/Serum#218]
Would be nice to provide a [Canonical URL](https://en.wikipedia.org/wiki/Canonical_link_element) to blog posts, so we can refer to original content.

Dev.to allows it to be set in the format:

```
canonical_url: https://github.com/Dalgona/Serum/issues/new
```

So it should generate inside the `<head>` block:

```html
<link rel="canonical" href="https://github.com/Dalgona/Serum/issues/new">
```

Also in https://github.com/Dalgona/serum-theme-essence would be nice to include something like this before starting content:

```md
Originally published at [github.com](https://github.com/Dalgona/Serum/issues/new)
```

Live example of canonical URL usage: https://dev.to/sourcelevel/10-items-to-check-before-assigning-a-pull-request-to-someone-plus-a-bonus-2963

If you find it interesting, I can implement this feature, since I'm needing this for my personal blog. WDYT?

**Comment by Dalgona** [comment]
This feature has been merged to `v1/master`. I'm not sure when to release the next version, but you can try it now by using the Git version:

```elixir
# In your mix.exs:

defp deps do
  [
    {:serum, github: "Dalgona/Serum", ref: "v1/master"}
  ]
end
```

- - -

From `CHANGELOG.md`:

- You can now specify "canonical URL" for your blog posts.

    ```
    ---
    title: Reposted Article
    date: 2022-09-04
    tags: sample
    canonical_url: https://example.com/original-article
    ---
    ```

    Then you can access the canonical URL in your templates using
    `@page.canonical_url`.

    ```eex
    <%= if @page.type === :post do %>
      <%
      canonical_url = @page.canonical_url || URI.merge(@project.server_root, @page.url)
      %>
      <link rel="canonical" href="<%= canonical_url %>">
    <% end %>
    ```

**Comment by wevtimoteo** [comment]
Nice job @Dalgona! 🎉 Will give it a try!
