### ISSUE TITLE
[theme] Support up to elixir1.16

### ISSUE THREAD

**Issue by nanarino** [Dalgona/Serum#237]
I got an error after upgrading the elixir version.

```
** (Mix) Invalid requirement any for app serum
```

If I use a theme I wrote myself own：

```
  ERROR  UndefinedFunctionError while loading theme (module: Serum.Themes.Wired): function Serum.Themes.Wired.name/0 is undefined (module Serum.Themes.Wired is not available)
```

**Comment by Dalgona** [comment]
Just updated the Elixir version requirement and dependencies. Update your `mix.exs` and try building your website again. If the problem continues to occur, please post the entire output of your invocation here, so that I can investigate the issue further.

**Comment by nanarino** [comment]
After the update, `:serum_theme_essence` cannot be installed.

**Comment by nanarino** [comment]
https://github.com/Dalgona/serum-theme-essence/issues/2#issue-2082620789


I already have the same symptoms as it🤔

**Comment by nanarino** [comment]
https://github.com/Dalgona/Serum/blob/v1/master/serum_new/priv/mix.exs.eex#L16C7-L16C29

After deleting this line, everything works as expected.
