### ISSUE TITLE
support for auto-generated pages

### ISSUE THREAD

**Issue by expilo** [Dalgona/Serum#24]
Would it be possible to add support for auto-generating pages,  something similar to Middleman's Dynamic Pages https://middlemanapp.com/advanced/dynamic-pages/ ?

**Comment by Dalgona** [comment]
Sorry for the late feedback. This feature looks great and I wish I could add support for dynamic pages in the future too, but it's far behind my priority queue right now so I cannot guarantee I can start working on it soon.

**Comment by Dalgona** [comment]
I will reopen this issue when the time comes. Sorry for disappointing you... for now!
