### ISSUE TITLE
Live Reloader

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#27]
CC: @suazithustra

We continue the discussion from #3 here.

We could implement the live reloader feature by adding some WebSocket thingies to the Serum development server.

1. A web browser navigates to a page served by the Serum development server.
2. The server establishes a WebSocket connection between the client.
3. The `fs` application detects file system changes and reports back to the server.
4. The server sends a "reload" message to the browser, and the browser refreshes the page.

To achieve the implementation of the above behavior, it's inevitable to modify the development server application (such as adding WebSocket functions, injecting WebSocket client to the web page being served, and so on).

However, most of the functionalities of the Serum development server has been moved to a separate project called "[microscope](https://github.com/Dalgona/microscope)" long ago, and I want microscope stay as a _dumb_ server serving static contents. So we might need to fork the code from microscope and start working on with that.

**Comment by suazithustra** [comment]
Why not just introduce hooks in microscope that can be used anywhere outside of it?

**Comment by Dalgona** [comment]
Sorry, I made you wait a lot. 💦

The _real_ live reloading is implemented in [v0.11.0](https://github.com/Dalgona/Serum/blob/master/CHANGELOG.md#v0110--2019-04-14). Yes, as you said, I had to put a small secret hole in Microscope to add Cowboy WebSocket handler.

[This video is a sneak peek of how it  works (link to a tweet).](https://twitter.com/d57pub_/status/1116992020201918464)

---

While many things have been added and changed since the opening of this issue, the docs and manual are not up to date yet. So this is a quick step-by-step guide on how to try this feature:

```sh
# Install the latest serum installer from Hex.
$ mix archive.install hex serum_new

# Create a new Serum project.
$ mix serum.new /path/to/project

# Install Serum.
$ cd /path/to/project
/path/to/project$ mix do deps.get, deps.compile

# Start the Serum development server.
/path/to/project$ mix serum.server

# Now open a web browser and navigate to "localhost:8080".
# Edit any file (pages, templates, serum.exs, etc.)
# and check if the browser refreshes itself.
```

I'll be waiting for your comments and opinions!

**Comment by Dalgona** [comment]
I'm closing this. If you have any problem with this feature, feel free to reopen this. Thanks.

**Comment by suazithustra** [comment]
It's working beautifully, thanks! I'll let you know if I notice any problems.
