### ISSUE TITLE
fs Issue on macOS

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#3]
The code on `dev/autobuild` branch may not work properly on macOS with `fsevents` as a backend. `:fs.start_link/2` fails with `{:port_exit, 130}` upon execution, when that code runs on the escript. There was no problem when I ran that code in `iex`. I have no idea why.

I just found the same code runs well on Linux with `inotify` as a backend.

**Comment by marocchino** [comment]
synrc/fs#30

**Comment by Dalgona** [comment]
[Dalgona/fs:a5f7e7b](https://github.com/Dalgona/fs/commit/a5f7e7b0bfd01737b4b8ca507ceec589be88c6e5) and 8c4594a temporarily resolves this problem. I'm still waiting for any responses to synrc/fs#30 though.

**Comment by Dalgona** [comment]
Decided to keep using my mod of fs. Tested on macOS today and it worked. Now users are required to install `fsevent_watch` using `brew`.

**Comment by suazithustra** [comment]
My watcher isn't working. I have `fsevent_watch` installed via brew on macOS 10.13.6. Is there a workaround?

**Comment by Dalgona** [comment]
I could not find any problem with fsevent_watch. My environment is:

- macOS High Sierra 10.13.6
- Elixir 1.7.4 on Erlang/OTP 21 (doesn't seem to matter though)
- `fsevent_watch` is installed and accessible through `$PATH`.
- Using commit 78e24ab (latest `master`)

Please make sure you're using the latest snapshot of Serum and try again. If the problem continues, please post the output of `serum server` command here for further investigation.

**Comment by suazithustra** [comment]
```
Serum -- Yet another simple static website generator
Version 0.6.1. Copyright (C) 2018 Dalgona. <dalgona@hontou.moe>
 MKDIR /tmp/serum_R88oReCe
Loading template files...
  READ templates/base.html.eex
  READ templates/list.html.eex
  READ templates/page.html.eex
  READ templates/post.html.eex
Loading include files...
  READ includes/footer.html.eex
  READ includes/nav.html.eex
Loading page files...
  READ pages/about.html
  READ pages/index.html
Loading post files...
 * Cannot access `posts/'. No post will be generated.
Compiling templates...
Processing page files...
Processing post files...
Generating fragments...
Generating post lists...
Writing output files...
 MKDIR /tmp/serum_R88oReCe
 MKDIR /tmp/serum_R88oReCe/posts
   GEN pages/index.html -> /tmp/serum_R88oReCe/index.html
   GEN pages/about.html -> /tmp/serum_R88oReCe/about.html
   GEN /tmp/serum_R88oReCe/posts/index.html
   GEN /tmp/serum_R88oReCe/posts/page-1.html
Copying assets and media...
Build process took 154.096ms.
[ * ] Server started listening on port 8080.
8080> help
Available commands are:
  help   Displays this help message
  build  Rebuilds the project
  quit   Stops the server and quit
8080>  * Changes were detected in the source directory.
 MKDIR /tmp/serum_R88oReCe
Loading template files...
  READ templates/base.html.eex
  READ templates/list.html.eex
  READ templates/page.html.eex
  READ templates/post.html.eex
Loading include files...
  READ includes/footer.html.eex
  READ includes/nav.html.eex
Loading page files...
  READ pages/about.html
  READ pages/index.html
Loading post files...
Compiling templates...
 * Cannot access `posts/'. No post will be generated.
Processing page files...
Processing post files...
Generating fragments...
Generating post lists...
Writing output files...
 MKDIR /tmp/serum_R88oReCe
 MKDIR /tmp/serum_R88oReCe/posts
   GEN pages/index.html -> /tmp/serum_R88oReCe/index.html
   GEN pages/about.html -> /tmp/serum_R88oReCe/about.html
   GEN /tmp/serum_R88oReCe/posts/index.html
   GEN /tmp/serum_R88oReCe/posts/page-1.html
Copying assets and media...
Build process took 16.73ms.
[200] 127.0.0.1 GET /
```
The ` * Changes were detected in the source directory.` line appears when I refresh the browser window.

**Comment by Dalgona** [comment]
That is the very intended behavior and the filesystem watcher is working properly. The purpose of the FS watcher is to detect changes(create, modify, remove, etc.) in the project directory, mark the directory as *dirty* only if such changes are detected.

Therefore the watcher itself does not initiate project rebuild every time it detects changes. The rebuild process is deferred until you refresh the browser.

**Comment by suazithustra** [comment]
Ah, i see. Would you be willing to merge a pull request to add a live reloader?

**Comment by Dalgona** [comment]
In the latest snapshot (on a branch not published here yet), escript has been removed in favor of Mix tasks. So the original issue is considered to be resolved.

I've opened a new thread for the discussion about live reloader (#27), as this is not so relevant to the original issue.
