### ISSUE TITLE
Markdown Headers should generate an id

### ISSUE THREAD

**Issue by igalic** [Dalgona/Serum#44]
Most markdown processors produce an `id` for head header which can, deterministically be addressed, even without a TOC.

```markdown
## Example header

some text
```

should produce

```html
<h2 id="example-header">Example header</h1>
<p>some text</p>
```

**Comment by Dalgona** [comment]
Good one. I'll find what we can do for this issue after resolving #43.

**Comment by Dalgona** [comment]
I just pushed the implementation to `master`. Element IDs are generated as follows:

1. All characters are downcased and each space is replaced with a hyphen (`-`). Any non-latin characters and symbols are preserved as-is (The HTML5 specification says that's okay).

    | Markup | Generated ID |
    |-|-|
    | `<h1>Test HTML Document</h1>` | `test-html-document` |
    | `<h2>테스트 1</h2>` | `테스트-1` |

2. IDs are always unique within a page. If a duplicate ID is to be generated, a number is appended.

    | Markup | Generated ID |
    |-|-|
    | `<h3>Example</h3>` | `example` |
    | `<h3>Example</h3>` | `example-2` |
    | `<h3>Example</h3>` | `example-3` |

3. If a heading tag already has an ID, no change is made.

    | Markup | Generated ID |
    |-|-|
    | `<h2 id="section-two">Lorem Ipsum</h2>` | (no change) |
    | `<h4 id="foo">FooBarBaz</h4>` | (no change) |
