### ISSUE TITLE
Support copying extra files to the output directory

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#46]
Once this feature is implemented, users will be able to put any files at the root directory of the generated website, without relying on external build scripts.

Examples: `CNAME` for GitHub pages, `favicon.ico`, `robots.txt`, and so on.

## Possible Implementation

- Let the user (website author) have a directory named `files/` under the project directory.
- Copy the contents of that directory to the output directory after copying assets and media (if any).
- Side effect: Any duplicate files generated by plugins and `Serum.Build.FileEmitter` will be overwritten by assets and media, and they will again be overwritten by files in the `files/` directory.

**Comment by igalic** [comment]
aaaaand `files/` could have sub directories, so i could put my talk-presentations online!

**Comment by Dalgona** [comment]
Of course! I'm highly likely to use `File.cp_r/2` to implement this one.

**Comment by Dalgona** [comment]
**TO DO:**
- [X] Implementation
- [X] Update test(s)
- [ ] Update docs in [serum-site](https://github.com/Dalgona/serum-site)

**Comment by Dalgona** [comment]
Just updated the [docs](https://github.com/Dalgona/serum-site/blob/master/pages/docs/project-structure.md#files-directory). This will be published on the next release date.
