### ISSUE TITLE
Last elements in nested lists not not in a paragraph

### ISSUE THREAD

**Issue by Duponin** [Dalgona/Serum#49]
Hi,

First thank you for that great sotfware.

I find a weird behavior when lists are nested. All but first elements are not set in a `<p>` tag.
Waited behavior was to have a `<p>` to every items in lists.

Markdown:
![screenshot_2019-07-07T22:20:35](https://user-images.githubusercontent.com/32687841/60773403-7c126700-a105-11e9-8373-a179af143cb1.png)

Web page:
![screenshot_2019-07-07T22:21:07](https://user-images.githubusercontent.com/32687841/60773406-8fbdcd80-a105-11e9-9517-2bbda577711d.png)

How HTML is made:
![screenshot_2019-07-07T22:19:11](https://user-images.githubusercontent.com/32687841/60773398-5ab17b00-a105-11e9-8edc-aaf5e3618a08.png)

I'll try find a way to fix it but I'm still an Elixir beginner.

**Comment by Dalgona** [comment]
That doesn't seem to be Serum's problem.

Serum uses [Earmark](https://hex.pm/packages/earmark) to transform markdown documents into HTMLs, and whether to wrap each list item with a `<p>` tag is determined by the markdown specification and the implementation details of Earmark.

Try putting a blank line between each list items. This might help you.
