### ISSUE TITLE
Let users include templates in includes

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#67]
How to handle cycles?

1. Leave that to users. (i.e. a user may encounter infinite loops, but that's the user's fault.)
1. Detect cycle and abort if found one. (user-friendly, with some implementation challenges™.)

I prefer the second option. :smile:

**Comment by igalic** [comment]
👍 for the second option as well — if it can be done, with sensible amounts of effort

**Comment by Dalgona** [comment]
_A small teaser here:_

![Screenshot_20190817_235935](https://user-images.githubusercontent.com/2667858/63213765-42446f80-c14b-11e9-9f4e-5fcd195982d1.png)

Hopefully this will be merged to `master` after some refactoring and test updates.
